# Generated by Django 4.2.13 on 2024-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentialDataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetype',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='codetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
