# Generated by Django 4.2.11 on 2024-04-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataDictionaryApp', '0003_datadict_code_datadict_value_alter_datadict_invildid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadict',
            old_name='udpatedUser',
            new_name='updatedUser',
        ),
    ]
