# Generated by Django 4.2.11 on 2024-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDictionaryApp', '0004_rename_udpateduser_datadict_updateduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadict',
            name='disableTime',
            field=models.DateTimeField(null=True, verbose_name='失效时间'),
        ),
        migrations.AlterField(
            model_name='datadict',
            name='enableTime',
            field=models.DateTimeField(null=True, verbose_name='生效时间'),
        ),
        migrations.AlterField(
            model_name='datadict',
            name='remark',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
    ]
