# Generated by Django 4.2.11 on 2024-04-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataDictionaryApp', '0005_alter_datadict_disabletime_alter_datadict_enabletime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadict',
            options={'ordering': ['type', 'name', 'code', 'value', 'invildId', 'enableTime', 'disableTime', 'remark']},
        ),
    ]
