# Generated by Django 4.2.11 on 2024-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDictionaryApp', '0006_alter_datadict_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadict',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
