# Generated by Django 4.2.13 on 2024-05-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataDictionaryApp', '0009_alter_datadict_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadict',
            options={'ordering': ['type', 'name', 'code', 'value', 'invildId', 'enableTime', 'disableTime', 'remark'], 'verbose_name': '基础配置字典'},
        ),
    ]
