# Generated by Django 4.2.13 on 2024-05-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentialDataApp', '0002_alter_codetype_code_alter_codetype_name'),
        ('dataDictionaryApp', '0010_alter_datadict_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadict',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentialDataApp.codetype'),
        ),
    ]
